config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "questions#index"

  resources :attachments, only: :destroy

  resources :links, only: :destroy

  resources :rewards, only: :index

  resources :questions do
    resources :answers do
      member do
        patch :mark_as_best
      end
    end
  end

  resources :votes, only: [] do
    collection do
      post ":votable_type/:votable_id/vote_up", to: "votes#vote_up", as: :vote_up
      post ":votable_type/:votable_id/vote_down", to: "votes#vote_down", as: :vote_down
      delete ":votable_type/:votable_id/cancel_vote", to: "votes#cancel_vote", as: :cancel_vote
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for(:title) || "Thinknetica Rails"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    link rel="manifest" href="/manifest.json"
    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body
    nav.navbar.navbar-expand-lg.navbar-dark.bg-primary.mb-4
      .container
        = link_to "Thinknetica Rails", root_path, class: "navbar-brand"
        .navbar-nav.ms-auto
          - if user_signed_in?
            = link_to "All Questions", questions_path, class: "nav-link"
            = link_to "My Rewards", rewards_path, class: "nav-link"
            = link_to "Sign out", destroy_user_session_path, method: :delete,
              class: "nav-link"
          - else
            = link_to "Sign in", new_user_session_path, class: "nav-link"

    .container.px-3
      p.notice = notice
      p.alert = alert

      = yield